version: "3"

services:
  mongo:
    container_name: athenna_mongo
    image: mongo
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345

  mysql:
    container_name: athenna_mysql
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: athenna
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  postgres:
    container_name: athenna_postgres
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_ROOT_PASSWORD: 12345
