version: "3"

services:
  postgres:
    container_name: athenna_postgres
    image: postgres
    volumes:
      - ./.docker/postgresql:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_ROOT_PASSWORD: 12345

