version: "3"

services:
  mysql:
    container_name: athenna_db_mysql
    image: mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: athenna
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  postgres:
    container_name: athenna_db_postgres
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_ROOT_PASSWORD: 12345
