version: '3'

services:
  mysql:
    container_name: athenna_mysql
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: athenna
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
