name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  linux:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        env:
          MYSQL_DATABASE: athenna
          MYSQL_ROOT_PASSWORD: 12345
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
          - '3307:3306'
      postgres:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 12345
          POSTGRES_ROOT_PASSWORD: 12345
        ports:
          - '5433:5432'
    strategy:
      matrix:
        node-version:
          - 14.15.4
          - 18.x
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test:coverage
